-- | Throwing and catching exceptions. Internal QuickCheck module.

-- Hide away the nasty implementation-specific ways of catching
-- exceptions behind a nice API. The main trouble is catching ctrl-C.

{-# LANGUAGE CPP #-}
module Test.QuickCheck.Exception(
  AnException,
  tryEvaluate,
  tryEvaluateIO,
  evaluate,
  isInterrupt,
  discard,
  isDiscard,
  finally) where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.Exception
