{-# LANGUAGE CPP #-}
#ifndef NO_ST_MONAD
{-# LANGUAGE Rank2Types #-}
#endif
-- | Test case generation.
module Test.QuickCheck.Gen where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.Gen
