-- | A wrapper around the system random number generator. Internal QuickCheck module.
{-# LANGUAGE CPP #-}
#ifndef NO_SAFE_HASKELL
{-# LANGUAGE Trustworthy #-}
#endif
module Test.QuickCheck.Random(
  newTheGen, mkTheGen,
#ifndef NO_TF_RANDOM
  bits, mask, doneBit,
#endif
  chip, chop, stop,
  QCGen(..),
  newQCGen, mkQCGen,
  bigNatVariant, natVariant,
  variantTheGen, boolVariant, variantQCGen) where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.Random
