-- | QuickCheck's internal state. Internal QuickCheck module.
module Test.QuickCheck.State(State(..)) where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.State
