-- | The main test loop.
{-# LANGUAGE CPP #-}
#ifndef NO_SAFE_HASKELL
{-# LANGUAGE Safe #-}
#endif
module Test.QuickCheck.Test where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.Test
