-- | The main test loop.
{-# LANGUAGE CPP #-}
#ifndef NO_SAFE_HASKELL
{-# LANGUAGE Safe #-}
#endif
module Test.QuickCheck.Test(
  Args(..),
  Result(..),
  isSuccess,
  stdArgs,
  quickCheck,
  quickCheckWith,
  quickCheckResult,
  quickCheckWithResult,
  verboseCheck,
  verboseCheckWith,
  verboseCheckResult,
  verboseCheckWithResult,
  test,
  doneTesting,
  giveUp,
  runATest,
  summary,
  success,
  labelPercentage,
  insufficientCoverage,
  foundFailure,
  localMin,
  localMin',
  localMinFound,
  callbackPostTest,
  callbackPostFinalFailure) where

-- Autogenerated - please run full/update to regenerate
import Test.QuickCheck.Light.Test
